Enter Server Host Address: [92mConnected to server![00m
> Enter a command: > Enter a username: [92mSuccess! Account created[00m
> Enter a command: > Input a text filter: > Input a page to return: [94m4 users on page 0 matching ''[00m
alice
bob
carson
dave
> Enter a command: > Input a text filter: > Input a page to return: [94m1 users on page 1 matching ''[00m
eve
> Enter a command: > Input a text filter: > Input a page to return: [94m1 users on page 0 matching 'eve'[00m
eve
> Enter a command: 