Enter Server Host Address: [92mConnected to server![00m
> Enter a command: > Enter a username: [92mSuccess! Logged in as alice[00m
> Enter a command: 
╔═══════════════════════╗
║ From: bob             ║
║ Message: how are you? ║
╚═══════════════════════╝
> Enter a command: > Recipient id: > What would you like to say?
[92mSuccess! Message sent[00m
> Enter a command: 
╔═══════════════╗
║ From: bob     ║
║ Message: good ║
╚═══════════════╝

╔═════════════════════════════════════════════════╗
║ From: carson                                    ║
║ Message: bob's been acting weird lately, right? ║
╚═════════════════════════════════════════════════╝
> Enter a command: 