Enter Server Host Address: [92mConnected to server![00m
> Enter a command: > Enter a command: > Enter a username: [92mSuccess! Logged in as bob[00m
> Enter a command: > Recipient id: > What would you like to say?
[92mSuccess! Message sent[00m
> Enter a command: 
╔═════════════════════════════╗
║ From: alice                 ║
║ Message: good. how are you? ║
╚═════════════════════════════╝
> Enter a command: > Recipient id: > What would you like to say?
[91mError: Message cannot be longer than 280 characters[00m
> Enter a command: > Recipient id: > What would you like to say?
[92mSuccess! Message sent[00m
> Enter a command: 